#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += it6151_i2c.o
obj-y += it6151_lp079qx1_edp_dsi_video.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc


